import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';
import ReactQueryProvider from './ReactQueryProvider';

export const metadata: Metadata = {
  title: '똘개비',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <Script
          strategy='beforeInteractive'
          type='text/javascript'
          src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=${process.env.MAP_CLIENT_ID}&submodules=geocoder`}
        ></Script>
      </head>
      <body className={`antialiased`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
